#! /bin/bash

while true; do
	read  entropy_avail < /proc/sys/kernel/random/entropy_avail
	read  poolsize < /proc/sys/kernel/random/poolsize
	printf "%s\t\r" "Available entropy: $(bc <<< "scale=2; ${entropy_avail} / ${poolsize}")"
	read -s -n 1 -t 1 || continue
	exit
done

manual:

	entropy_avail
              This read-only file gives the available entropy, in bits.   This
              will be a number in the range 0 to 4096.

       poolsize
              This  file gives the size of the entropy pool.  The semantics of
              this file vary across kernel versions:

              Linux 2.4:
                     This file gives the size of the entropy  pool  in  bytes.
                     Normally,  this  file  will have the value 512, but it is
                     writable, and can be changed to any value  for  which  an
                     algorithm  is  available.   The  choices are 32, 64, 128,
                     256, 512, 1024, or 2048.

              Linux 2.6 and later:
                     This file is read-only, and gives the size of the entropy
                     pool in bits.  It contains the value 4096.

       read_wakeup_threshold
              This  file  contains  the number of bits of entropy required for
              waking  up  processes  that  sleep  waiting  for  entropy   from
              /dev/random.  The default is 64.

       write_wakeup_threshold
              This  file contains the number of bits of entropy below which we
              wake up processes that do a select(2) or poll(2) for  write  ac‐
              cess  to /dev/random.  These values can be changed by writing to
              the files.

       uuid and boot_id
              These   read-only   files   contain    random    strings    like
              6fd5a44b-35f4-4ad4-a9b9-6b9be13e1fe9.   The  former is generated
              afresh for each read, the latter was generated once.

