#! /bin/bash

i=0
while read file; do
	tab[$i]=$file
	echo "$((++i))) $(mp3info -p "%l (%a): %t" "$file")"
done < <(find . -name "*\.mp3" -print)

while read -p "Choose a number to play> " answer; do
	if [ $answer -ge 1 ] 2>/dev/null && [ $answer -le ${#tab[@]} ]; then
		mplayer ${tab[$((answer - 1))]} > /dev/null 2> /dev/null
	else
		echo "Wrong answer"
	fi

done
